ITL-11 Implement Todo Archive, Sorting, Search, Checking
nykami/todo-app pull request #11
Opened 2023-09-11 07:53 UTC by nykami

2023-09-11 08:28 UTC, tamasm-wg requested changes

2023-09-11 08:28 UTC, tamasm-wg commented on client/src/views/Dashboard.vue
> +    v-if="todos.length && filteredTodos.length"
please create a computed for this condition

2023-09-11 08:28 UTC, tamasm-wg commented on client/src/service/TodoService.ts
> +        `http://localhost:8080/user/todos/check/${todoId}`,
please use .env for URL-s

2023-09-11 08:28 UTC, tamasm-wg commented on client/src/service/TodoService.ts
> +      await postRequest(`http://localhost:8080/user/todos/archive/${todoId}`);
please use .env for URL-s

2023-09-11 08:28 UTC, tamasm-wg commented on client/src/views/Dashboard.vue
> +  </div>
The content of these div-s is almost the same , please add the v-if to the components that change not to the whole div

2023-09-11 08:28 UTC, tamasm-wg commented on client/src/views/Dashboard.vue
> +      throw new Error('Todo not found in the todos list.');
please add {} to your if conditions even if it's a one liner, it will help readability if you need to add another functionalities in the future

2023-09-11 08:28 UTC, tamasm-wg commented on client/src/views/Dashboard.vue
> +    } else {
if you are using an early return you don't need to add the else branch

2023-09-11 08:28 UTC, tamasm-wg commented on client/src/views/Dashboard.vue
> +    isSortingApplied.value = sortByField.value ? true : false;
isSortingApplied.value = !!sortByField.value
https://www.samanthaming.com/tidbits/19-2-ways-to-convert-to-boolean/

2023-09-11 10:49 UTC, gerebdavid commented on server/controller/todoController.ts
> +      var sortingMethods = {
Why do you use var?

2023-09-11 10:53 UTC, nykami commented on server/controller/todoController.ts
> +      var sortingMethods = {
Sorry, my bad. Should be const.

2023-09-11 11:03 UTC, gerebdavid approved these changes

2023-09-12 08:05 UTC, tamasm-wg approved these changes

2023-09-12 09:57 UTC, merged